name: bank
services:
  mariadb:
    container_name: "bank-db"
    image: mariadb:11.6.2
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    security_opt:
      - no-new-privileges=true
volumes:
  mariadb_data:
